#############################################################################
# Makefile for building: plazza
# Generated by qmake (2.01a) (Qt 4.6.3) on: Fri Apr 15 15:10:00 2011
# Project:  plazza.pro
# Template: app
# Command: /usr/lib/qt4/bin/qmake -unix -o Makefile plazza.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -g3 -pipe -Wall -Wextra -Werror -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -Iincludes -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)   -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Command.cpp \
		Communicator.cpp \
		CondVar.cpp \
		Err.cpp \
		Gui.cpp \
		Home.cpp \
		ItemDelegate.cpp \
		Kitchen.cpp \
		Mutex.cpp \
		Pipe2.cpp \
		PizzaFactory.cpp \
		Plazza.cpp \
		ScopedLock.cpp \
		Treewidget.cpp moc_Gui.cpp \
		moc_ItemDelegate.cpp
OBJECTS       = Command.o \
		Communicator.o \
		CondVar.o \
		Err.o \
		Gui.o \
		Home.o \
		ItemDelegate.o \
		Kitchen.o \
		Mutex.o \
		Pipe2.o \
		PizzaFactory.o \
		Plazza.o \
		ScopedLock.o \
		Treewidget.o \
		moc_Gui.o \
		moc_ItemDelegate.o
DIST          = /usr/lib/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/release.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf \
		plazza.pro
QMAKE_TARGET  = plazza
DESTDIR       = 
TARGET        = plazza

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: plazza.pro  /usr/lib/qt4/mkspecs/linux-g++/qmake.conf /usr/lib/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/release.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -unix -o Makefile plazza.pro
/usr/lib/qt4/mkspecs/common/g++-multilib.conf:
/usr/lib/qt4/mkspecs/common/unix.conf:
/usr/lib/qt4/mkspecs/common/linux.conf:
/usr/lib/qt4/mkspecs/qconfig.pri:
/usr/lib/qt4/mkspecs/features/qt_functions.prf:
/usr/lib/qt4/mkspecs/features/qt_config.prf:
/usr/lib/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt4/mkspecs/features/default_pre.prf:
/usr/lib/qt4/mkspecs/features/release.prf:
/usr/lib/qt4/mkspecs/features/default_post.prf:
/usr/lib/qt4/mkspecs/features/warn_on.prf:
/usr/lib/qt4/mkspecs/features/qt.prf:
/usr/lib/qt4/mkspecs/features/unix/thread.prf:
/usr/lib/qt4/mkspecs/features/moc.prf:
/usr/lib/qt4/mkspecs/features/resources.prf:
/usr/lib/qt4/mkspecs/features/uic.prf:
/usr/lib/qt4/mkspecs/features/yacc.prf:
/usr/lib/qt4/mkspecs/features/lex.prf:
/usr/lib/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile plazza.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/plazza1.0.0 || $(MKDIR) .tmp/plazza1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/plazza1.0.0/ && $(COPY_FILE) --parents includes/Command.hh includes/Communicator.hh includes/CondVar.hh includes/Err.hh includes/Gui.hh includes/ItemDelegate.hh includes/Kitchen.hh includes/KitchenState.hh includes/Mutex.hh includes/Pipe2.hh includes/PizzaFactory.hh includes/Plazza.hh includes/SafeQueue.hpp includes/ScopedLock.hh includes/Thread.hpp includes/Treewidget.hh .tmp/plazza1.0.0/ && $(COPY_FILE) --parents Command.cpp Communicator.cpp CondVar.cpp Err.cpp Gui.cpp Home.cpp ItemDelegate.cpp Kitchen.cpp Mutex.cpp Pipe2.cpp PizzaFactory.cpp Plazza.cpp ScopedLock.cpp Treewidget.cpp .tmp/plazza1.0.0/ && (cd `dirname .tmp/plazza1.0.0` && $(TAR) plazza1.0.0.tar plazza1.0.0 && $(COMPRESS) plazza1.0.0.tar) && $(MOVE) `dirname .tmp/plazza1.0.0`/plazza1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/plazza1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core

fclean:	clean
	$(RM) $(TARGET)

re: fclean all

####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_Gui.cpp moc_ItemDelegate.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Gui.cpp moc_ItemDelegate.cpp
moc_Gui.cpp: includes/KitchenState.hh \
		includes/Gui.hh
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) includes/Gui.hh -o moc_Gui.cpp

moc_ItemDelegate.cpp: includes/Gui.hh \
		includes/KitchenState.hh \
		includes/ItemDelegate.hh
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) includes/ItemDelegate.hh -o moc_ItemDelegate.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

Command.o: Command.cpp includes/Command.hh \
		includes/Plazza.hh \
		includes/Communicator.hh \
		includes/Pipe2.hh \
		includes/KitchenState.hh \
		includes/Gui.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Command.o Command.cpp

Communicator.o: Communicator.cpp includes/Plazza.hh \
		includes/Communicator.hh \
		includes/Pipe2.hh \
		includes/KitchenState.hh \
		includes/Gui.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Communicator.o Communicator.cpp

CondVar.o: CondVar.cpp includes/CondVar.hh \
		includes/Mutex.hh \
		includes/ScopedLock.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CondVar.o CondVar.cpp

Err.o: Err.cpp includes/Plazza.hh \
		includes/Communicator.hh \
		includes/Pipe2.hh \
		includes/KitchenState.hh \
		includes/Gui.hh \
		includes/Err.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Err.o Err.cpp

Gui.o: Gui.cpp includes/Gui.hh \
		includes/KitchenState.hh \
		includes/Treewidget.hh \
		includes/ItemDelegate.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Gui.o Gui.cpp

Home.o: Home.cpp includes/Plazza.hh \
		includes/Communicator.hh \
		includes/Pipe2.hh \
		includes/KitchenState.hh \
		includes/Gui.hh \
		includes/Kitchen.hh \
		includes/Thread.hpp \
		includes/Command.hh \
		includes/SafeMap.hpp \
		includes/Mutex.hh \
		includes/CondVar.hh \
		includes/ScopedLock.hh \
		includes/PizzaFactory.hh \
		includes/Err.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Home.o Home.cpp

ItemDelegate.o: ItemDelegate.cpp includes/ItemDelegate.hh \
		includes/Gui.hh \
		includes/KitchenState.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ItemDelegate.o ItemDelegate.cpp

Kitchen.o: Kitchen.cpp includes/Kitchen.hh \
		includes/Thread.hpp \
		includes/Plazza.hh \
		includes/Communicator.hh \
		includes/Pipe2.hh \
		includes/KitchenState.hh \
		includes/Gui.hh \
		includes/Command.hh \
		includes/SafeMap.hpp \
		includes/Mutex.hh \
		includes/CondVar.hh \
		includes/ScopedLock.hh \
		includes/PizzaFactory.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Kitchen.o Kitchen.cpp

Mutex.o: Mutex.cpp includes/Mutex.hh \
		includes/Err.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Mutex.o Mutex.cpp

Pipe2.o: Pipe2.cpp includes/Pipe2.hh \
		includes/Err.hh \
		includes/Plazza.hh \
		includes/Communicator.hh \
		includes/KitchenState.hh \
		includes/Gui.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Pipe2.o Pipe2.cpp

PizzaFactory.o: PizzaFactory.cpp includes/PizzaFactory.hh \
		includes/Command.hh \
		includes/Plazza.hh \
		includes/Communicator.hh \
		includes/Pipe2.hh \
		includes/KitchenState.hh \
		includes/Gui.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PizzaFactory.o PizzaFactory.cpp

Plazza.o: Plazza.cpp includes/Communicator.hh \
		includes/Pipe2.hh \
		includes/Command.hh \
		includes/Plazza.hh \
		includes/KitchenState.hh \
		includes/Gui.hh \
		includes/Err.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Plazza.o Plazza.cpp

ScopedLock.o: ScopedLock.cpp includes/ScopedLock.hh \
		includes/Mutex.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ScopedLock.o ScopedLock.cpp

Treewidget.o: Treewidget.cpp includes/Treewidget.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Treewidget.o Treewidget.cpp

moc_Gui.o: moc_Gui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Gui.o moc_Gui.cpp

moc_ItemDelegate.o: moc_ItemDelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ItemDelegate.o moc_ItemDelegate.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

